apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/redirect-to-https: "true"
    ingress.bluemix.net/rewrite-path: "serviceName=marmotta rewrite=/;serviceName=new-service rewrite=/"
  name: rules-prod
spec:
  tls:
  - hosts:
    - nimble.uk-south.containers.mybluemix.net
    secretName: nimble-cert
  rules:
  - host: nimble.uk-south.containers.mybluemix.net
    http:
      paths:
      - backend:
          serviceName: marmotta
          servicePort: 8080
        path: /marmotta/
