apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prod
  annotations:
    ingress.bluemix.net/redirect-to-https: "true"
    ingress.bluemix.net/rewrite-path: |
      serviceName=registration-service rewrite=/;
  name: rules-prod
spec:
  tls:
  - hosts:
    - nimble-platform.uk-south.containers.mybluemix.net
    secretName: nimble-platform
  rules:
  - host: nimble-platform.uk-south.containers.mybluemix.net
    http:
      paths:
        - path: /registration-service/
          backend:
            serviceName: registration-service
            servicePort: 8080     
        
