kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-slave-data
  labels:
    type: ibmc-file-gold
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
