apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: jenkins-slave-admin
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiVersion: v1
  kind: ServiceAccount
  name: jenkins-slave-sa
  namespace: build
